server:
  port: 8800

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: false
    ratelimiters:
      enabled: true

spring:
  cloud:
    gateway:
      #      default-filters:
      #        - name: GlobalFilter
      #          args:
      #            baseMessage: Spring Cloud Edu Gateway GlobalFilter
      #            preLogger: true
      #            postLogger: true

      routes:
        - id: employee-service 
          uri: http://backend-springboot
          ##uri: http://edu25-ingressgateway
          ##uri: http://istio-ingressgateway.istio-system.svc
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*),/$\{path}

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    com.kt: trace
