server:
  port: 8800

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: false
    ratelimiters:
      enabled: true

spring:
  cloud:
    gateway:
      #      default-filters:
      #        - name: GlobalFilter
      #          args:
      #            baseMessage: Spring Cloud Edu Gateway GlobalFilter
      #            preLogger: true
      #            postLogger: true

      routes:
        - id: employee-service
          uri: http://backend-springboot
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*),/$\{path}
            #- Path=/backend
            # filters:
            #   - TokenRelay=
            #         filters:
            #           - name: GlobalFilter
            #              args:
            #                baseMessage: Spring Cloud Edu Gateway GlobalFilter
            #                preLogger: true
            #                postLogger: true
            # - RewritePath=/api/v1/(?<path>.*),/$\{path}
#        - id: neo-user-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/backend/**
#          filters:
#            - RewritePath=/api/v1/?(?<segment>.*), /$\{segment}

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: debug
    com.kt: trace
